name: bigbang
dependencies:
- backports=1.0=py27_0
- beautiful-soup=4.3.2=py27_0
- boto3=1.3.1=py27_0
- botocore=1.4.19=py27_0
- cairo=1.12.18=4
- configparser=3.5.0b2=py27_1
- coverage=4.1=py27_0
- cycler=0.10.0=py27_0
- dateutil=2.4.1=py27_0
- decorator=3.4.0=py27_0
- docutils=0.12=py27_2
- entrypoints=0.2=py27_1
- fontconfig=2.11.1=5
- freetype=2.5.2=2
- futures=3.0.5=py27_0
- get_terminal_size=1.0.0=py27_0
- ipykernel=4.3.1=py27_0
- ipython=4.2.0=py27_0
- ipython-notebook=4.0.4=py27_0
- ipython_genutils=0.1.0=py27_0
- jinja2=2.7.3=py27_1
- jmespath=0.9.0=py27_0
- jsonschema=2.4.0=py27_0
- jupyter_client=4.2.2=py27_0
- jupyter_core=4.1.0=py27_0
- libgfortran=3.0.0=1
- libpng=1.6.17=0
- libsodium=0.4.5=0
- libxml2=2.9.2=0
- markupsafe=0.23=py27_0
- matplotlib=1.5.1=np111py27_0
- mistune=0.5.1=py27_1
- mkl=11.3.3=0
- nbconvert=4.2.0=py27_0
- nbformat=4.0.1=py27_0
- networkx=1.11=py27_0
- nltk=3.0.0=np19py27_0
- nose=1.3.7=py27_1
- notebook=4.2.1=py27_0
- numpy=1.11.0=py27_1
- openssl=1.0.2d=0
- pandas=0.18.1=np111py27_0
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.7.2=py27_0
- pip=8.1.2=py27_0
- pixman=0.26.2=0
- ptyprocess=0.4=py27_0
- py2cairo=1.10.0=py27_2
- pycairo=1.10.0=py27_0
- pydot=1.0.28=py27_0
- pygments=2.0.2=py27_0
- pyparsing=1.5.6=py27_0
- pyqt=4.11.4=py27_0
- pyside=1.2.1=py27_1
- python=2.7.11=0
- python-dateutil=2.5.3=py27_0
- pytz=2016.4=py27_0
- pyyaml=3.11=py27_4
- pyzmq=14.6.0=py27_0
- qt=4.8.6=0
- readline=6.2=2
- requests=2.10.0=py27_0
- scikit-learn=0.17.1=np111py27_1
- scipy=0.17.1=np111py27_0
- setuptools=17.0=py27_0
- shiboken=1.2.1=py27_0
- simplegeneric=0.8.1=py27_1
- sip=4.16.9=py27_0
- six=1.9.0=py27_0
- sqlite=3.8.4.1=1
- ssl_match_hostname=3.4.0.2=py27_0
- system=5.8=2
- terminado=0.5=py27_0
- tk=8.5.18=0
- tornado=4.1=py27_0
- traitlets=4.2.1=py27_0
- wheel=0.29.0=py27_0
- yaml=0.1.6=0
- zeromq=4.0.5=0
- zlib=1.2.8=0
- pip:
  - async==0.6.1
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - beautifulsoup==3.2.1
  - beautifulsoup4==4.3.2
  - bigbang (/home/sb/projects/bigbang)==0.1
  - chardet==2.3.0
  - common==0.1.1
  - community==1.0.0b1
  - flake8==2.2.5
  - flask==0.10.1
  - gitdb==0.5.4
  - gitpython==0.3.2rc1
  - html2text==2015.2.18
  - ipython-genutils==0.1.0
  - itsdangerous==0.24
  - jupyter-client==4.2.2
  - jupyter-core==4.1.0
  - louvain==0.5.2
  - mccabe==0.2.1
  - mpmath==0.19
  - pep8==1.5.7
  - powerlaw==1.3.4
  - pyflakes==0.8.1
  - python-igraph==0.7.1.post4
  - python-levenshtein==0.11.2
  - seaborn==0.5.1
  - smmap==0.8.2
  - snakefood==1.4
  - werkzeug==0.10.4

