# The given paths are to be appended to the filepath of
# the bigbang directory, which is calculated from the filepath
# of the config.yml file. For example, if a path is
# "archives/sample-git-repos", and the filepath of this file is
# "~/folder/other/bigbang/config/config.yml" the full interpretation
# of it should be "~/folder/other/bigbang/archives/sample-git-repos".
# Note that "config/config.yml" was taken out.

# PATHS.
# For Configuration to work properly, paths need to have "path"
# in their keyword.
# NOTE: BE CAFEFUL NOT TO PUT 'path' IN OTHER ATTRIBUTE NAMES
config_path : "bigbang/"
repo_path : "archives/sample-git-repos/"
mail_path : "archives/"
datatracker_path : "archives/datatracker"
urls_path : "examples/"
test_data_path: "tests/data/"

ietfdata_cache_path : "archives/datatracker/cache"

# REGEX
# These are certain important regular expressions
# TODO: They are not completely standardized or stable yet. They do not yet work
git_url_to_name_rgx: '([^/]*)(\\.git$)'
file_to_name_rgx : '.*\/(.*)'


# ATTRIBUTES
# These are the attributes collected
all_attributes: ["HEXSHA", "Committer Name", "Committer Email", "Commit Message", "Time", "Parent Commit", "Touched File"]
